### ISSUE TITLE
Crash on Servers

### ISSUE THREAD

**Issue by GekidoLukas** [noeppi-noeppi/MineMention#2] opened 2021-06-11 16:25 UTC
I typed @everyone and then the server crashed.
Sorry, that I don't have more information.

The Crash report:
https://pastebin.com/qUHjtZFr

**Comment by noeppi-noeppi** [comment] 2021-06-11 16:27
Duplicate of [Libx/12](https://github.com/noeppi-noeppi/LibX/issues/12)

Update LibX

**Closed as completed by noeppi-noeppi** 2021-06-11 16:27 UTC
Labels: duplicate
