### ISSUE TITLE
Mod crashes

### ISSUE THREAD

**Issue by Tobonos** [noeppi-noeppi/MineMention#5] opened 2021-09-02 21:29 UTC
Hey
Minemention crashes when I start minecraft
Heres the message:
Minemention (minemention) has failed to load correctly java.lang.NoClassDefFoundError: com/feed_the_beast/mods/ftbteams/event/TeamDeletedEvent

Can you help me please?
[crash-2021-09-02_23.27.57-fml.txt](https://github.com/noeppi-noeppi/MineMention/files/7101844/crash-2021-09-02_23.27.57-fml.txt)
[latest.log](https://github.com/noeppi-noeppi/MineMention/files/7101845/latest.log)

**Comment by noeppi-noeppi** [comment] 2021-09-09 15:23
Duplicate of #4

**Closed as completed by noeppi-noeppi** 2021-09-09 15:23 UTC
Labels: duplicate
